# name = "csapf"
main = "dist/_worker.js/index.js"
# main = "dist/"
compatibility_date = "2024-10-24"
# compatibility_flags = ["nodejs.compat"]

[[d1_databases]]
binding = "devd1" # available in your Worker on env.DB
database_name = "dev"
database_id = "478cb27d-b9c4-49e0-8336-7c9ae4125d62"
preview_database_id = "devd1"
migrations_dir = ".drizzle/migrations"
